//
//  HeavyViewController.m
//  HeavyRotation
//
//  Created by Marjan Hratson on 9/7/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "HeavyViewController.h"


@implementation HeavyViewController

-(void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)x 
                                        duration:(NSTimeInterval)duration 
{
    // change BG color depending on Orientation
    UIColor *c = (UIInterfaceOrientationIsLandscape(x) ? [UIColor redColor] : [UIColor greenColor]);
    [self.view setBackgroundColor:c];
}

// allow autorotation 
-(BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)x {
    return YES;
}

// NOTE:
// - since default view controller implementation loads NIB file having same name as the
//   controller it's totally safe to remove all autogenerated boilerplate
// - also yet there's no instance variables so no reason to owerride defaults

@end
